# 使用官方的 Python 镜像作为基础镜像
FROM python:3.7-slim

# 设置工作目录
WORKDIR /app

# 将当前目录下的所有文件复制到容器中的 /app 目录
ADD . /app

# 安装所有必要的依赖
RUN pip install --no-cache-dir -r requirements.txt

# 设置环境变量
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

# 对外暴露端口
EXPOSE 5000

# 运行命令
CMD ["flask", "run"]
